# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    operator = "="
    va1 = 0
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(378, 504)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.output_label = QtWidgets.QLabel(self.centralwidget)
        self.output_label.setGeometry(QtCore.QRect(10, 20, 361, 71))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.output_label.setFont(font)
        self.output_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.output_label.setFrameShape(QtWidgets.QFrame.Box)
        self.output_label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.output_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.output_label.setObjectName("output_label")
        self.oneButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.clicked_action("1"))
        self.oneButton.setGeometry(QtCore.QRect(10, 100, 80, 81))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.oneButton.setFont(font)
        self.oneButton.setObjectName("oneButton")
        self.twoButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.clicked_action("2"))
        self.twoButton.setGeometry(QtCore.QRect(100, 100, 80, 81))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.twoButton.setFont(font)
        self.twoButton.setObjectName("twoButton")
        self.threeButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.clicked_action("3"))
        self.threeButton.setGeometry(QtCore.QRect(190, 100, 80, 81))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.threeButton.setFont(font)
        self.threeButton.setObjectName("threeButton")
        self.clearButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.clicked_action("C"))
        self.clearButton.setGeometry(QtCore.QRect(280, 100, 80, 81))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.clearButton.setFont(font)
        self.clearButton.setObjectName("clearButton")
        self.fiveButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.clicked_action("5"))
        self.fiveButton.setGeometry(QtCore.QRect(100, 190, 80, 81))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.fiveButton.setFont(font)
        self.fiveButton.setObjectName("fiveButton")
        self.plusButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.clicked_action("+"))
        self.plusButton.setGeometry(QtCore.QRect(280, 190, 80, 81))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.plusButton.setFont(font)
        self.plusButton.setObjectName("plusButton")
        self.fourButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.clicked_action("4"))
        self.fourButton.setGeometry(QtCore.QRect(10, 190, 80, 81))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.fourButton.setFont(font)
        self.fourButton.setObjectName("fourButton")
        self.sixButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.clicked_action("6"))
        self.sixButton.setGeometry(QtCore.QRect(190, 190, 80, 81))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.sixButton.setFont(font)
        self.sixButton.setObjectName("sixButton")
        self.eightButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.clicked_action("8"))
        self.eightButton.setGeometry(QtCore.QRect(100, 280, 80, 81))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.eightButton.setFont(font)
        self.eightButton.setObjectName("eightButton")
        self.minusButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.clicked_action("-"))
        self.minusButton.setGeometry(QtCore.QRect(280, 280, 80, 81))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.minusButton.setFont(font)
        self.minusButton.setObjectName("minusButton")
        self.sevenButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.clicked_action("7"))
        self.sevenButton.setGeometry(QtCore.QRect(10, 280, 80, 81))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.sevenButton.setFont(font)
        self.sevenButton.setObjectName("sevenButton")
        self.nineButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.clicked_action("9"))
        self.nineButton.setGeometry(QtCore.QRect(190, 280, 80, 81))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.nineButton.setFont(font)
        self.nineButton.setObjectName("nineButton")
        self.decimalButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.clicked_action("."))
        self.decimalButton.setGeometry(QtCore.QRect(100, 370, 80, 81))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.decimalButton.setFont(font)
        self.decimalButton.setObjectName("decimalButton")
        self.multiplyButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.clicked_action("X"))
        self.multiplyButton.setGeometry(QtCore.QRect(280, 370, 80, 81))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.multiplyButton.setFont(font)
        self.multiplyButton.setObjectName("multiplyButton")
        self.zeroButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.clicked_action("0"))
        self.zeroButton.setGeometry(QtCore.QRect(10, 370, 80, 81))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.zeroButton.setFont(font)
        self.zeroButton.setObjectName("zeroButton")
        self.equalButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.clicked_action("="))
        self.equalButton.setGeometry(QtCore.QRect(190, 370, 80, 81))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.equalButton.setFont(font)
        self.equalButton.setObjectName("equalButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 378, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.output_label.setText(_translate("MainWindow", "0"))
        self.oneButton.setText(_translate("MainWindow", "1"))
        self.twoButton.setText(_translate("MainWindow", "2"))
        self.threeButton.setText(_translate("MainWindow", "3"))
        self.clearButton.setText(_translate("MainWindow", "C"))
        self.fiveButton.setText(_translate("MainWindow", "5"))
        self.plusButton.setText(_translate("MainWindow", "+"))
        self.fourButton.setText(_translate("MainWindow", "4"))
        self.sixButton.setText(_translate("MainWindow", "6"))
        self.eightButton.setText(_translate("MainWindow", "8"))
        self.minusButton.setText(_translate("MainWindow", "-"))
        self.sevenButton.setText(_translate("MainWindow", "7"))
        self.nineButton.setText(_translate("MainWindow", "9"))
        self.decimalButton.setText(_translate("MainWindow", "."))
        self.multiplyButton.setText(_translate("MainWindow", "X"))
        self.zeroButton.setText(_translate("MainWindow", "0"))
        self.equalButton.setText(_translate("MainWindow", "="))

    def clicked_action(self, stuff):
        if stuff == "C":
            self.output_label.setText("0")

        elif stuff == "+" or stuff == "X" or stuff == "-":
            self.va1 = self.output_label.text()
            self.output_label.setText("0")
            self.operator = stuff

        elif stuff == "=":
            if self.operator == "+":
                self.output_label.setText(str(float(self.va1) + float(self.output_label.text())))
            elif self.operator == "-":
                self.output_label.setText(str(float(self.va1) - float(self.output_label.text())))
            elif self.operator == "X":
                self.output_label.setText(str(float(self.va1) * float(self.output_label.text())))
            else:
                pass

        elif "." in self.output_label.text() and stuff == ".":
            pass

        else:
            if self.output_label.text() == "0":
                self.output_label.setText("")
            self.output_label.setText(f'{self.output_label.text()}{stuff}')

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
